import numpy as np
import torch

general_labels_map = {'HEAD_TOP': 'ARIEL',
                      'TOPBACK': 'C7',
                      'NECK_BASE': 'C7',
                      'CHEST': 'CLAV',
                      'UPTHRX': 'CLAV',
                      'L_ANKLE': 'LANK',
                      'L_ANK': 'LANK',
                      'L_UPBACK': 'LBAK',
                      'LBAC': 'LBAK',
                      'LBAC-1': 'LBAK',
                      'L_BICEP': 'LBCEP',
                      'L_EAR': 'LBHD',
                      'NEWLSHO': 'LBCEP',
                      'NEWRSHO': 'RBCEP',
                      'NEWLBAC': 'LNWST',
                      'NEWRBAC': 'RNWST',
                      'LBSHO': 'LBSH',
                      'L_B_SHOULDER': 'LBSH',
                      'L_B_WAIST': 'LBWT',
                      'L_BWT': 'LBWT',
                      'LPSI': 'LBWT',
                      'L_CALF': 'LCLF',
                      'LIBH': 'LEBHI',
                      'LMBH': 'LEBHM',
                      'LPBH': 'LEBHP',
                      'LRBH': 'LEBHR',
                      'LIDIP': 'LEIDIP',
                      'L_ELBOW': 'LELB',
                      'L_INELBOW': 'LELBIN',
                      'LILB': 'LELBIN',
                      'LIEL': 'LELBIN',
                      'LMDIP': 'LEMDIP',
                      'LPDIP': 'LEPDIP',
                      'LPPIP': 'LEPPIP',
                      'LPTIP': 'LEPTIP',
                      'LRDIP': 'LERDIP',
                      'LRPIP': 'LERPIP',
                      'LRTIP': 'LERTIP',
                      'LTMP': 'LETMP',
                      'LTPIPI': 'LETPIPIN',
                      'LTPIPO': 'LTHM4',
                      'HEAD_OFFSET': 'LFHD',
                      'L_PINKY': 'LFIN',
                      'LOHAND': 'LFIN',
                      'L_FIN': 'LFIN',
                      'LPHLX5': 'LFIN',
                      'L_FOREARM': 'LFRM',
                      'LARM': 'LFRM',
                      'LFRA': 'LFRM',
                      'LWRE': 'LFRM',
                      'LWRI': 'LFRMIN',
                      'L_F_SHOULDER': 'LFSH',
                      'LASI': 'LFWT',
                      'L_F_WAIST': 'LFWT',
                      'L_FWT': 'LFWT',
                      'L_HEEL': 'LHEE',
                      'LHEL': 'LHEE',
                      'LANKIN': 'LHEEI',
                      'LANKI': 'LHEEI',
                      'LIPIP': 'LIDX1',
                      'LEIPIP': 'LIDX1',
                      'LITIP': 'LIDX3',
                      'LEITIP': 'LIDX3',
                      'L_INWRIST': 'LIWR',
                      'LWRA': 'LIWR',
                      'LWRST': 'LIWR',
                      'L_OUTKNEE': 'LKNE',
                      'L_KNEE': 'LKNE',
                      'L_INKNEE': 'LKNI',
                      'LKNEIN': 'LKNI',
                      'LMPIP': 'LMID1',
                      'LEMPIP': 'LMID1',
                      'LMTIP': 'LMID3',
                      'LEMTIP': 'LMID3',
                      'L_BIGTOE': 'LMT1',
                      'L_PINKYTOE': 'LMT5',
                      'L_OUTWRIST': 'LOWR',
                      'LWRB': 'LOWR',
                      'L_WRIST': 'LOWR',
                      # 'LEPTIP': 'LPNK3',
                      'LMWT': 'LPRFWT',
                      'LTOE5': 'LRSTBEEF',
                      'L_MIDBACK': 'LSCAP',
                      'L_SHIN': 'LSHN',
                      'LSHIN': 'LSHN',
                      'L_SHOULDER': 'LSHOUP',
                      'LHIP': 'LTHI',
                      'L_HIP': 'LTHI',
                      'L_HAM': 'LTHI',
                      'L_THIGH': 'LTHILO',
                      'LTHIGH': 'LTHILO',
                      'LTTIP': 'LTHM3',
                      # 'LETTIP': 'LTHM3',
                      'L_THUMB': 'LTHMB',
                      'LIHAND': 'LTHMB',
                      'LPHLX1': 'LTHMB',
                      'LLEG': 'LTIB',
                      'L_TOETIP': 'LTOE',
                      'LTOE1': 'LTOE',
                      'L_TRICEP': 'LUPA',
                      'R_ANKLE': 'RANK',
                      'R_ANK': 'RANK',
                      'R_UPBACK': 'RBAK',
                      'RBAC': 'RBAK',
                      'RBAC-1': 'RBAK',
                      'R10': 'RBAK',
                      'OFFSET': 'RBAK',
                      'R_BICEP': 'RBCEP',
                      'R_EAR': 'RBHD',
                      'RBSHO': 'RBSH',
                      'R_B_SHOULDER': 'RBSH',
                      'RPSI': 'RBWT',
                      'R_B_WAIST': 'RBWT',
                      'R_BWT': 'RBWT',
                      'R_CALF': 'RCLF',
                      'R_ELBOW': 'RELB',
                      'R_INELBOW': 'RELBIN',
                      'RILB': 'RELBIN',
                      'RIEL': 'RELBIN',
                      'R_PINKY': 'RFIN',
                      'ROHAND': 'RFIN',
                      'R_FIN': 'RFIN',
                      'RPHLX5': 'RFIN',
                      'R_FOREARM': 'RFRM',
                      'RARM': 'RFRM',
                      'RFRA': 'RFRM',
                      'RWRE': 'RFRM',
                      'RWRI': 'RFRMIN',
                      'R_F_SHOULDER': 'RFSH',
                      'RASI': 'RFWT',
                      'R_F_WAIST': 'RFWT',
                      'R_FWT': 'RFWT',
                      'R_HEEL': 'RHEE',
                      'RHEL': 'RHEE',
                      'RANKIN': 'RHEEI',
                      'RANKI': 'RHEEI',
                      'RIBH': 'RIBHI',
                      'RMBH': 'RIBHM',
                      'RPBH': 'RIBHP',
                      'RRBH': 'RIBHR',
                      'RITIP': 'RIDX3',
                      'RIITIP': 'RIDX3',
                      'RIDIP': 'RIIDIP',
                      'RIPIP': 'RIIPIP',
                      'RMDIP': 'RIMDIP',
                      'RMPIP': 'RIMPIP',
                      'RPDIP': 'RIPDIP',
                      'RPPIP': 'RIPPIP',
                      'RRDIP': 'RIRDIP',
                      'RRPIP': 'RIRPIP',
                      'RTMP': 'RITMP',
                      'RTPIPI': 'RITPIPIN',
                      'RTPIPO': 'RITPIPOUT',
                      'RTTIP': 'RITTIP',
                      'R_INWRIST': 'RIWR',
                      'RWRA': 'RIWR',
                      'R_OUTKNEE': 'RKNE',
                      'R_KNEE': 'RKNE',
                      'R_INKNEE': 'RKNI',
                      'RKNEIN': 'RKNI',
                      'RMTIP': 'RMID3',
                      'RIMTIP': 'RMID3',
                      'R_BIGTOE': 'RMT1',
                      'R_PINKYTOE': 'RMT5',
                      'R_OUTWRIST': 'ROWR',
                      'RWRB': 'ROWR',
                      'R_WRIST': 'ROWR',
                      'RPTIP': 'RPNK3',
                      'RIPTIP': 'RPNK3',
                      'RMWT': 'RPRFWT',
                      'RRTIP': 'RRNG3',
                      'RIRTIP': 'RRNG3',
                      'RTOE5': 'RRSTBEEF',
                      'R_MIDBACK': 'RSCAP',
                      'R_SHIN': 'RSHN',
                      'RSHIN': 'RSHN',
                      'R_SHOULDER': 'RSHOUP',
                      'RHIP': 'RTHI',
                      'R_HIP': 'RTHI',
                      'R_HAM': 'RTHI',
                      'R_THIGH': 'RTHILO',
                      'RTHIGH': 'RTHILO',
                      'R_THUMB': 'RTHMB',
                      'RIHAND': 'RTHMB',
                      'RPHLX1': 'RTHMB',
                      'RLEG': 'RTIB',
                      'R_TOETIP': 'RTOE',
                      'RTOE1': 'RTOE',
                      'R_TRICEP': 'RUPA',
                      'STERNUM': 'STRN',
                      'SETRNUM': 'STRN',
                      'LOTHRX': 'STRN',
                      'LOBACK': 'T10',
                      'MIDBACK': 'T8',
                      'MID_BACK': 'T8',
                      'ghost': 'nan',
                      'NaN': 'nan',
                      }

all_marker_vids ={'ARIEL': 411,
    'BHEAD': 384,
    'C7': 3470,
    'CHIN': 3052,
    'CLAV': 3171,
    'FHEAD': 335,
    'LAEL': 1655,
    'LANK': 3327,
    'LAOL': 1736,
    'LBAK': 1812,
    'LBCEP': 628,
    'LBHD': 182,
    'LBLLY': 1345,
    'LBSH': 2940,
    'LBTHI': 988,
    'LBUM': 3116,
    'LBUST': 3040,
    'LBUSTLO': 1426,
    'LBWT': 3122,
    'LCHEECK': 239,
    'LCHST': 595,
    'LCLAV': 1298,
    'LCLF': 1103,
    'LEBHI': 2274,
    'LEBHM': 2270,
    'LEBHP': 2193,
    'LEBHR': 2293,
    'LEIDIP': 2295,
    'LELB': 1666,
    'LELBIN': 1725,
    'LEMDIP': 2407,
    'LEPDIP': 2635,
    'LEPPIP': 2590,
    'LEPTIP': 2674,
    'LERDIP': 2518,
    'LERPIP': 2478,
    'LERTIP': 2557,
    'LETMP': 2070,
    'LETPIPIN': 2713,
    'LETPIPOUT': 2711,
    'LFHD': 0,
    'LFIN': 2174,
    'LFOOT': 3365,
    'LFRM': 1568,
    'LFRM2': 1741,
    'LFRM2IN': 1953,
    'LFRMIN': 1728,
    'LFSH': 1317,
    'LFTHI': 874,
    'LFTHIIN': 1368,
    'LFWT': 857,
    'LHEE': 3387,
    'LHEEI': 3432,
    'LHPS': 2176,
    'LHTS': 2134,
    'LIDX1': 2204,
    'LIDX2': 2283,
    'LIDX3': 2320,
    'LIWR': 2112,
    'LKNE': 1053,
    'LKNI': 1058,
    'LMHAND': 2212,
    'LMID1': 2389,
    'LMID2': 2406,
    'LMID3': 2446,
    'LMT1': 3336,
    'LMT5': 3346,
    'LNECK': 298,
    'LNWST': 1323,
    'LOWR': 2108,
    'LPNK1': 2628,
    'LPNK2': 2634,
    'LPNK3': 2674,
    'LPRFWT': 2915,
    'LRNG1': 2499,
    'LRNG2': 2517,
    'LRNG3': 2564,
    'LRSTBEEF': 3314,
    'LSCAP': 1252,
    'LSHN': 1082,
    'LSHNIN': 1153,
    'LSHO': 1861,
    'LSHOUP': 742,
    'LTHI': 1454,
    'LTHILO': 850,
    'LTHM1': 2251,
    'LTHM2': 2706,
    'LTHM3': 2730,
    'LTHM4': 2732,
    'LTHMB': 2224,
    'LTIB': 1112,
    'LTIBIN': 1105,
    'LTIP': 1100,
    'LTOE': 3233,
    'LUPA': 1443,
    'LUPA2': 1315,
    'LWPS': 1943,
    'LWTS': 1922,
    'MBLLY': 1769,
    'MBWT': 3022,
    'MFWT': 3503,
    'MNECK': 3057,
    'RAEL': 5087,
    'RANK': 6728,
    'RAOL': 5127,
    'RBAK': 5273,
    'RBCEP': 4116,
    'RBHD': 3694,
    'RBLLY': 4820,
    'RBSH': 6399,
    'RBTHI': 4476,
    'RBUM': 6540,
    'RBUST': 6488,
    'RBUSTLO': 4899,
    'RBWT': 6544,
    'RCHEECK': 3749,
    'RCHST': 4085,
    'RCLAV': 4780,
    'RCLF': 4589,
    'RELB': 5135,
    'RELBIN': 5194,
    'RFHD': 3512,
    'RFIN': 5635,
    'RFOOT': 6765,
    'RFRM': 5037,
    'RFRM2': 5210,
    'RFRM2IN': 5414,
    'RFRMIN': 5197,
    'RFSH': 4798,
    'RFTHI': 4360,
    'RFTHIIN': 4841,
    'RFWT': 4343,
    'RHEE': 6786,
    'RHEEI': 6832,
    'RHPS': 5525,
    'RHTS': 5595,
    'RIBHI': 5735,
    'RIBHM': 5731,
    'RIBHP': 5655,
    'RIBHR': 5752,
    'RIDX1': 5722,
    'RIDX2': 5744,
    'RIDX3': 5781,
    'RIIDIP': 5757,
    'RIIPIP': 5665,
    'RIMDIP': 5869,
    'RIMPIP': 5850,
    'RIPDIP': 6097,
    'RIPPIP': 6051,
    'RIRDIP': 5980,
    'RIRPIP': 5939,
    'RITMP': 5531,
    'RITPIPIN': 6174,
    'RITPIPOUT': 6172,
    'RITTIP': 6191,
    'RIWR': 5573,
    'RKNE': 4538,
    'RKNI': 4544,
    'RMHAND': 5674,
    'RMID1': 5861,
    'RMID2': 5867,
    'RMID3': 5907,
    'RMT1': 6736,
    'RMT5': 6747,
    'RNECK': 3810,
    'RNWST': 4804,
    'ROWR': 5568,
    'RPNK1': 6089,
    'RPNK2': 6095,
    'RPNK3': 6135,
    'RPRFWT': 6375,
    'RRNG1': 5955,
    'RRNG2': 5978,
    'RRNG3': 6018,
    'RRSTBEEF': 6682,
    'RSCAP': 4735,
    'RSHN': 4568,
    'RSHNIN': 4638,
    'RSHO': 5322,
    'RSHOUP': 4230,
    'RTHI': 4927,
    'RTHILO': 4334,
    'RTHM1': 5714,
    'RTHM2': 6168,
    'RTHM3': 6214,
    'RTHM4': 6193,
    'RTHMB': 5686,
    'RTIB': 4598,
    'RTIBIN': 4593,
    'RTIP': 4585,
    'RTOE': 6633,
    'RUPA': 4918,
    'RUPA2': 4794,
    'RWPS': 5526,
    'RWTS': 5690,
    'SACR': 1783,
    'STRN': 3506,
    'T10': 3016,
    'T8': 3508}

smpl_labels_map={
    'LIEL':'LELBIN',
    'RIEL':'RELBIN',
    
    
}


smpl_cmocap_point_ind=np.array(list(all_marker_vids.values())) 
smpl_cmocap_point_ind=torch.tensor(smpl_cmocap_point_ind)

import ezc3d

pc_seq=ezc3d.c3d("E:\dataset\datasets\SOMA_manual_labeled\soma_subject1\clap_001.c3d")#['header', 'parameters', 'data']
#print(pc_seq['parameters']['POINT']['LABELS']['value'])  
labels=pc_seq['parameters']['POINT']['LABELS']['value']

#print(labels)

#pick_labels=['ARIEL', 'LFHD', 'LBHD', 'RFHD', 'RBHD', 'C7', 'T10', 'CLAV', 'STRN', 'LFSH', 'LBSH', 'LUPA', 'LELB', 'LFRM', 'LIWR', 'LOWR', 'RFSH', 'RBSH', 'RUPA', 'RELB', 'RFRM', 'RIWR', 'ROWR', 'LFWT', 'MFWT', 'RFWT', 'LBWT', 'MBWT', 'RBWT', 'LTHI', 'LKNE', 'LKNI', 'LSHN', 'LANK', 'LMT5', 'LMT1', 'LTOE', 'RTHI', 'RKNE', 'RKNI', 'RSHN', 'RANK', 'RMT5', 'RMT1', 'RTOE']
pick_labels = []
pick_lindex=[]
dictt=dict()
for i in range(len(labels)):
    label=labels[i]
    label=str.split(label,':')[1]
    dictt[label]=0
    #print(i)
    if(all_marker_vids.keys().__contains__(label)):
        index=all_marker_vids[label]
        pick_labels.append(label)
        pick_lindex.append(index)
        # if(label=='LIEL'):
        #     print("gg"+str(index))
    else:
        if(label=='LIEL'):
            pick_labels.append(label)
            index=1725
        if(label=='LIHAND'):
            pick_labels.append(label)
            index=2177
        if(label=='LOHAND'):
            pick_labels.append(label)
            index=2155
        if(label=='RIEL'):
            pick_labels.append(label)
            index=5194
        if(label=='RIHAND'):
            pick_labels.append(label)
            index=5638
        if(label=='ROHAND'):
            pick_labels.append(label)
            index=5614
        if(label=='LHEL'):
            pick_labels.append(label)
            index=3393
        if(label=='RHEL'):
            pick_labels.append(label)
            index=6793                                 
        # label=general_labels_map[label]
        #pick_labels.append(label)
        print(label)
        print(i)  
        pick_lindex.append(index)
      


pick_lindex=torch.tensor(np.array(pick_lindex))

print(pick_lindex)
print(pick_labels)
